apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-cluster
  namespace: rabbitmq
spec:
  replicas: 2
  image: rabbitmq:4-management
  resources:
    requests:
      cpu: 1000m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 1Gi
  persistence:
    storageClassName: standard
    storage: 5Gi
  service:
    type: LoadBalancer
  rabbitmq:
    envConfig: |  
      RABBITMQ_DEFAULT_USER=guest
      RABBITMQ_DEFAULT_PASS=guest
      RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS=true

