version: '3.8'

services:
  user:
    build:
      context: ./services/user
      dockerfile: Dockerfile
    container_name: user
    ports:
      - "8000:8000"
    volumes:
      - ./services/user:/var/www/html
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_started

  user-detail:
    build:
      context: ./services/user-detail
      dockerfile: Dockerfile
    container_name: user-detail
    ports:
      - "8001:8000"
    volumes:
      - ./services/user-detail:/var/www/html
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_started

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_running" ]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  mongodb_data: