apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: sehatin-app
build:
  artifacts:

  local:
    push: false

deploy:
  kubectl: { }

manifests:
  rawYaml:
    - k8s/mongodb/mongodb-namespace.yml
    - k8s/mongodb/*.yml
portForward:
  - resourceType: service
    resourceName: mongo-mongos
    namespace: default
    port: 27017
    localPort: 27017