apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: sehatin-app
build:
  local:
    push: false
  artifacts:
    - image: sehatin/user-service
      context: services/user
    - image: sehatin/user-detail-service
      context: services/user-detail

deploy:
  kubectl:
    manifests:
      - k8s/*.yml