apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: sehatin-app
build:
  artifacts: []

  local:
    push: false

deploy:
  kubectl: { }
  helm:
    releases:
      - name: ollama
        remoteChart: ollama
        repo: https://otwld.github.io/ollama-helm/
        namespace: ollama
        createNamespace: true
        valuesFiles:
          - ./k8s/ollama/values/ollama-values.yaml

manifests:
  rawYaml:
  # - k8s\ollama\ollama-deployment.yaml