apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: mongodb
data:
  mongo-init.js: |
    rs.initiate({
        _id: "rs0",
        members: [
            { _id: 0, host: "mongodb-0.mongodb-service.mongodb.svc.cluster.local:27017" },
            { _id: 1, host: "mongodb-1.mongodb-service.mongodb.svc.cluster.local:27017" },
            { _id: 2, host: "mongodb-2.mongodb-service.mongodb.svc.cluster.local:27017" }
        ]
    });