# k8s/mongodb/mongodb-mongos.yml (mongo-mongos Service and Deployment)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-mongos
  namespace: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      role: mongo-mongos
  template:
    metadata:
      labels:
        role: mongo-mongos
    spec:
      containers:
        - name: mongo-mongos
          image: mongo:latest
          command:
            - mongos
            - --configdb
            - configReplSet/mongo-config-0.mongo-config.mongodb.svc.cluster.local:27018,mongo-config-1.mongo-config.default.svc.cluster.local:27018,mongo-config-2.mongo-config.default.svc.cluster.local:27018
            - --bind_ip_all
            - --port
            - "27017"
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-mongos
  namespace: mongodb
spec:
  selector:
    role: mongo-mongos
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
