# Example Secret definition (ensure name and namespace are correct)
apiVersion: v1
kind: Secret
metadata:
  name: shared-secret # MUST match the name in the Middleware spec
  namespace: traefik   # MUST be in the 'traefik' namespace
type: Opaque
stringData:
  # Or use 'data' with base64 encoded values
  # The key 'users' is expected by Traefik's basicAuth
  users: "admin:$2a$12$ZyFxWstXeMxvvQOpVy/y3.tcPXFV.I9Q2SmeMlvzP1kCymRyQ/dum" # Example: user 'admin' with a hashed password 'admin'