apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot
  namespace: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
        - name: chatbot
          image: sehatin/chatbot-service # You'll need to build and push this image
          ports:
            - containerPort: 5000
          # resources:
          #   requests:
          #     cpu: "500m"
          #     memory: "2Gi"
          #   limits:
          #     cpu: "1000m"
          #     memory: "3Gi"
          env:
            - name: OLLAMA_URL
              value: "ollama.ollama.svc.cluster.local:11434"
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot
  namespace: ollama
spec:
  selector:
    app: chatbot
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer