apiVersion: apps/v1
kind: Deployment
metadata:
  name: seeder-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seeder-service
  template:
    metadata:
      labels:
        app: seeder-service
    spec:
      containers:
        - name: seeder-service
          image: sehatin/seeder-service
          ports:
            - containerPort: 8000
          command: ["php", "artisan", "octane:start", "--server=swoole", "--host=0.0.0.0", "--port=8000", "--watch"]
          envFrom:
            - configMapRef:
                name: shared-config
            - secretRef:
                name: shared-env
---
apiVersion: v1
kind: Service
metadata:
  name: seeder-service
spec:
  selector:
    app: seeder-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000